[package]
name = "biodivine-lib-sbml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# When enabled, rust the SBML syntactic test suite as part of unit tests.
# This is mainly used for the purpose of code coverage computation.
sbml_test_suite = []

[dependencies]
const_format = "0.2.31"
macros = { path = "macros" }
phf = { version = "0.11.2", features = ["macros"] }
strum = "0.25.0"
strum_macros = "0.25"
xml-doc = { git = "https://github.com/daemontus/xml-doc" }
regex = "1.10.3"
