[package]
name = "biodivine-lib-sbml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-doc = { git = "https://github.com/daemontus/xml-doc" }
